### ISSUE TITLE
Improve `install.dart` of `shared-code` template

### ISSUE THREAD

**Issue by Giuspepe** [phntmxyz/sidekick#128]
Right now the `shared-code` template generates this part in `install.dart`:

```dart
final commandFile = package.root.file('lib/src/my_plugin.dart');
commandFile.writeAsStringSync("""
import 'package:sidekick_core/sidekick_core.dart';
import 'package:my_plugin/my_plugin.dart';

class MyPluginCommand extends Command {
  @override
  final String description = 'Sample command';

  @override
  final String name = 'my-plugin;

  MyPluginCommand() {
    // add parameters here with argParser.addOption
  }

  @override
  Future<void> run() async {
    // please implement me
    final hello = getGreetings().shuffled().first;
    print('\\\$hello from PHNTM!');
    
    final bye = getFarewells().shuffled().first;
    print('\\\$bye from PHNTM!');
  }
}""");
```

It would be neat if you didn't have to copy paste the command code into `install.dart`, e.g.

```dart
final commandFile = package.root.file('lib/src/my_plugin.dart');
commandFile.writeAsStringSync(myPluginCommandFile.readAsStringSync());
```

I'm just not sure if/how we can get the correct path of `myPluginCommandFile`

**Comment by passsy** [comment]
We can inject a reference to the plugin installer package into the installation process. At least during installation, we can guarantee the installer code to be in `build/cache/`.

It might even be possible to read the current script location via [`script`](https://api.dart.dev/stable/2.18.5/dart-io/Platform/script.html) and traverse from there to the correct file (since installation is executed in the Dart VM).

But I wouldn't invest much time here. Existing solutions like `mason` exist for those running into the problem of writing a lot of code into the cli. And in the future, this feature should be doable easily with static meta programming.
