### ISSUE TITLE
systemFlutterSdk() should check for FLUTTER_ROOT

### ISSUE THREAD

**Issue by passsy** [phntmxyz/sidekick#93]
Some folks may use `env.FLUTTER_ROOT` and not put `flutter` in their `PATH`. We should support that.

**Comment by Giuspepe** [comment]
Who is using `env.FLUTTER_HOME`?

I've found that the Dart/Flutter extensions for VS Code used `env.FLUTTER_HOME` in older versions, but it  hasn't been used anymore since some years. Instead `env.FLUTTER_ROOT` is used by these extensions. So we should add `FLUTTER_ROOT` as well. 

See:
- [Dart/Flutter VS Code extensions changelog deprecating FLUTTER_HOME for FLUTTER_ROOT](https://github.com/Dart-Code/Website/blob/693f1863502975782879736ed01b030c2a184d12/_releases/v1.4.md?plain=1#L38)
- [current Flutter SDK search paths in Dart/Flutter VS Code extensions](url)

**Comment by passsy** [comment]
Correct! Changed it, we should look for `FLUTTER_ROOT`, not `FLUTTER_HOME`.
